

export const Actions = {
    SELECT_TICKET: 'SELECT_TICKET',
    ADD_TICKET: 'ADD_TICKET',
    EDIT_TICKET: 'EDIT_TICKET',
    SHOW_SAVE_TICKET: 'SHOW_ADD_TICKET',
    HIDE_SAVE_TICKET: 'HIDE_SAVE_TICKET',
    ADD_LANE: 'ADD_LANE',
    UNSELECT_TICKET: 'UNSELECT_TICKET',
    MOVE_TICKET: 'MOVE_TICKET',
    HIDE_EDIT_TICKET: 'HIDE_EDIT_TICKET',
    UPDATE_TICKET_PRIORITY: 'UPDATE_TICKET_PRIORITY',
    SEARCH_TICKETS: 'SEARCH_TICKETS',
    FILTER_PRIORITY: 'FILTER_PRIORITY',
}